CREATE DATABASE IF NOT EXISTS Promohawk;

USE Promohawk;

CREATE TABLE IF NOT EXISTS TB_USUARIO (
  ID_USUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOME_USUARIO VARCHAR(100) NOT NULL  UNIQUE KEY, # NÃO PRECISA SER OBRIGATORIO
  NOME_VERDADEIRO VARCHAR (60) NOT NULL,
  EMAIL_USUARIO VARCHAR(90) NOT NULL  UNIQUE KEY, 
  SENHA_USUARIO VARCHAR(60) NOT NULL, 
  TEL_USUARIO NUMERIC(18) NOT NULL,
  IMG_USUARIO MEDIUMBLOB NULL
)engine=InnoDB;

CREATE TABLE IF NOT EXISTS TB_LOJA (
	ID_LOJA INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,
	NOME_LOJA VARCHAR(100) NOT NULL  UNIQUE KEY,
    CUPOM_LOJA decimal(4,2) NULL,
    AVALIACAO_LOJA decimal(1,1) NULL,
    ID_USUARIO INT NOT NULL, # marcação
    FOREIGN KEY (`ID_USUARIO`) REFERENCES `tb_usuario` (`ID_USUARIO`)
)engine=InnoDB;

CREATE TABLE IF NOT EXISTS TB_PRODUTO (
  ID_PRODUTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOME_PRODUTO VARCHAR(100) NOT NULL,
  PRECO_PRODUTO DECIMAL(7,2) NOT NULL,
  IMG_PRODUTO MEDIUMBLOB NOT NULL,
  DESCRICAO_PRODUTO TEXT,
  RATING_PRODUTO INT NOT NULL, # marcação
  ID_CATEGORIA INT NOT NULL,
  ID_LOJA INT NOT NULL,
  FOREIGN KEY (`ID_CATEGORIA`) REFERENCES `tb_categoria` (`ID`),
  FOREIGN KEY (`ID_LOJA`) REFERENCES `tb_loja` (`ID`)
)engine=InnoDB;

CREATE TABLE IF NOT EXISTS TB_CATEGORIA (
  ID_CATEGORIA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOME_CATEGORIA VARCHAR(100) NOT NULL  UNIQUE KEY
) engine=InnoDB;

CREATE TABLE IF NOT EXISTS TB_AVALIACAO (
	ID_AVALIACAO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUTO INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    RATING_PRODUTO INT NOT NULL,
    COMENT_PRODUTO TEXT,
    FOREIGN KEY (`ID_PRODUTO`) REFERENCES `tb_produto` (`ID`),
    FOREIGN KEY (`ID_USUARIO`) REFERENCES `tb_usuario` (`ID`)
)engine=InnoDB;

CREATE TABLE TB_CUPOM (
	ID_CUPOM INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_LOJA INT NOT NULL,
    CODIGO_CUPOM VARCHAR(50) NOT NULL  UNIQUE KEY,
    VALIDADE_CUPOM DATE NOT NULL,
    DESCONTO DECIMAL(5,2) NOT NULL,
    FOREIGN KEY (`ID_LOJA`) REFERENCES `tb_loja` (`ID`)
    )engine=InnoDB;

