CREATE DATABASE IF NOT EXISTS Promohawk;

USE Promohawk;

-- ==========================================================
-- 						TABELAS PRINCIPAIS
-- ==========================================================

CREATE TABLE TB_USUARIO (
	ID_USUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME_USUARIO VARCHAR(30) NULL UNIQUE KEY,
	NOME_VERDADEIRO VARCHAR (100) NOT NULL,
	TEL_USUARIO VARCHAR(15) NOT NULL,
	EMAIL_USUARIO VARCHAR(100) NOT NULL UNIQUE KEY,
	SENHA_USUARIO VARCHAR(60) NOT NULL,
	IMG_USUARIO MEDIUMBLOB NULL
)engine=InnoDB;

select * from TB_USUARIO;

CREATE TABLE IF NOT EXISTS TB_CUPOM (
	ID_CUPOM INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CODIGO_CUPOM VARCHAR(50) NOT NULL UNIQUE,
    DESCONTO DECIMAL(5,2) NOT NULL,
    DATA_VALIDADE DATE NOT NULL,
    ID_LOJA INT NOT NULL,
    FOREIGN KEY (ID_LOJA) REFERENCES TB_LOJA (ID_LOJA)
) ENGINE=InnoDB;

SELECT * FROM TB_CUPOM;

CREATE TABLE IF NOT EXISTS TB_LOJA (
	ID_LOJA INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	NOME_LOJA VARCHAR(100) NOT NULL UNIQUE,
	AVALIACAO_LOJA DECIMAL(1,1) NULL,
    ID_CUPOM INT NULL,
    FOREIGN KEY (ID_CUPOM) REFERENCES TB_CUPOM (ID_CUPOM)
) ENGINE=InnoDB;

select * from TB_LOJA;

CREATE TABLE IF NOT EXISTS TB_CATEGORIA (
  ID_CATEGORIA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOME_CATEGORIA VARCHAR(100) NOT NULL UNIQUE KEY
) engine=InnoDB;

select * from TB_CATEGORIA;

CREATE TABLE TB_PRODUTO (
  ID_PRODUTO INT NOT NULL PRIMARY KEY,
  ID_CATEGORIA INT NOT NULL,
  NOME_PRODUTO VARCHAR(100) NOT NULL,
  PRECO_PRODUTO DECIMAL(7,2) NOT NULL,
  IMAGEM_PRODUTO MEDIUMBLOB NOT NULL,
  DESCRICAO_PRODUTO TINYTEXT,
  RATING_PRODUTO INT NOT NULL,
  ID_LOJA INT NOT NULL,
  FOREIGN KEY (ID_CATEGORIA) REFERENCES TB_CATEGORIA (ID_CATEGORIA),
  FOREIGN KEY (ID_LOJA) REFERENCES TB_LOJA (ID_LOJA)
) engine=InnoDB;

select * from TB_PRODUTO;


-- =============================================================
-- 						TABELAS EXTRAS
-- =============================================================

CREATE TABLE TB_HISTORICO_PRECO_PRODUTO (
  ID_HISTORICO INT AUTO_INCREMENT PRIMARY KEY,
  ID_PRODUTO INT,
  PRECO DECIMAL(7,2),
  DATA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO)
);

CREATE TABLE IF NOT EXISTS TB_REVIEWS (
	ID_REVIEWS INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUTO INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    RATING_PRODUTO INT NOT NULL,
    COMENT_PRODUTO VARCHAR(600),
    FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO (ID_PRODUTO),
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO)
)engine=InnoDB;

select * from TB_REVIEWS;

CREATE TABLE IF NOT EXISTS TB_FAVORITOS (
	ID_FAVORITOS INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
	FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO (ID_PRODUTO),
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO),
    UNIQUE (ID_USUARIO, ID_PRODUTO)
)engine=InnoDB;

select * from TB_FAVORITOS;


-- =============================================================
-- 					AUTOMATIZAÇÃO DE AÇÕES
-- =============================================================
# Ainda em desenvolvimento