CREATE DATABASE IF NOT EXISTS Promohawk;

USE Promohawk;

drop database Promohawk;

SELECT * FROM TB_USUARIO;
SELECT * FROM TB_LOJA;
SELECT * FROM TB_CUPOM;
SELECT * FROM TB_CATEGORIA;
SELECT * FROM TB_PRODUTO;
SELECT * FROM TB_FAVORITOS;
SELECT * FROM TB_REVIEWS;

-- ==========================================================
-- 						TABELAS PRINCIPAIS
-- ==========================================================

CREATE TABLE IF NOT EXISTS TB_USUARIO (
	ID_USUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME_USUARIO VARCHAR(30) NOT NULL,
	NOME_VERDADEIRO VARCHAR (100) NOT NULL,
	TEL_USUARIO VARCHAR(15) NOT NULL,
	EMAIL_USUARIO VARCHAR(100) NOT NULL,
	SENHA_USUARIO VARCHAR(60) NOT NULL,
	IMG_USUARIO MEDIUMBLOB NULL,
    UNIQUE (NOME_USUARIO, SENHA_USUARIO)
)engine=InnoDB;


CREATE TABLE IF NOT EXISTS TB_LOJA (
	ID_LOJA INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	NOME_LOJA VARCHAR(100) NOT NULL UNIQUE,
    IMG_LOJA MEDIUMBLOB NULL
)engine=InnoDB;


CREATE TABLE IF NOT EXISTS TB_CUPOM (
	ID_CUPOM INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CODIGO_CUPOM VARCHAR(50) NOT NULL UNIQUE,
    DESCONTO DECIMAL(5,2) NOT NULL,
    DATA_VALIDADE DATE NOT NULL,
    ID_LOJA INT NOT NULL,
    FOREIGN KEY (ID_LOJA) REFERENCES TB_LOJA (ID_LOJA)
)engine=InnoDB;


CREATE TABLE IF NOT EXISTS TB_CATEGORIA (
  ID_CATEGORIA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOME_CATEGORIA VARCHAR(100) NOT NULL UNIQUE KEY
)engine=InnoDB;


CREATE TABLE IF NOT EXISTS TB_PRODUTO (
  ID_PRODUTO INT NOT NULL PRIMARY KEY,
  NOME_PRODUTO VARCHAR(100) NOT NULL,
  PRECO_PRODUTO DECIMAL(7,2) NOT NULL,
  IMAGEM_PRODUTO MEDIUMBLOB NOT NULL,
  DESCRICAO_PRODUTO TEXT NOT NULL DEFAULT "Não possui descrição",
  LINK_PRODUTO VARCHAR(200) NOT NULL,
  ID_REVIEWS INT NULL,
  ID_CATEGORIA INT NOT NULL,
  ID_LOJA INT NOT NULL,
  FOREIGN KEY (ID_CATEGORIA) REFERENCES TB_CATEGORIA (ID_CATEGORIA),
  FOREIGN KEY (ID_LOJA) REFERENCES TB_LOJA (ID_LOJA)
)engine=InnoDB;



-- =============================================================
-- 						TABELAS EXTRAS
-- =============================================================

CREATE TABLE IF NOT EXISTS TB_REVIEWS (
	ID_REVIEWS INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    RATING_PRODUTO INT NOT NULL,
    COMENT_PRODUTO VARCHAR(600) NOT NULL,
    ID_PRODUTO INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO (ID_PRODUTO) ON DELETE CASCADE,
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO) ON DELETE CASCADE
)engine=InnoDB;


CREATE TABLE IF NOT EXISTS TB_FAVORITOS (
	ID_FAVORITOS INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
	FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO (ID_PRODUTO) ON DELETE CASCADE, 
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO) ON DELETE CASCADE,
    UNIQUE (ID_USUARIO, ID_PRODUTO)
)engine=InnoDB;


CREATE TABLE IF NOT EXISTS TB_HISTORICO_PRECO_PRODUTO (
  ID_HISTORICO INT AUTO_INCREMENT PRIMARY KEY,
  PRECO DECIMAL(7,2),
  DATA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
  ID_PRODUTO INT,
  FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO) ON DELETE CASCADE
)engine=InnoDB;


-- =============================================================
-- 					AUTOMATIZAÇÃO DE AÇÕES
-- =============================================================
# Ainda em desenvolvimento